### ISSUE TITLE
ID name does not accept space

### ISSUE THREAD

**Issue by swhe** [ibm-watson-iot/html5-phone#1]
when people enter a device ID to identify their device, the ID name does not accept space for now.when I tried "xinlin iphone", i got error message "Failed to authenticate! Gateway Time-out" Then I tried "xinlin-iphone", i  successfully passed authentication.

So sound like ID name does not allow space.we need to at least let user know, there is certain naming rule for device ID

**Comment by alanblyth** [comment]
I have also resolved this in my pull request  #6 
The user is alerted then reprompted until they enter something valid.

**Comment by durera** [comment]
PR merged
