### ISSUE TITLE
App crashes when trying to run

### ISSUE THREAD

**Issue by JSHHansen** [ibm-watson-iot/html5-phone#13]
I get these error messages from my log.

`2018-01-15T10:11:54.40+0100 [APP/PROC/WEB/0] ERR /home/vcap/app/node_modules/cloudant/cloudant.js:45`
`2018-01-15T10:11:54.40+0100 [APP/PROC/WEB/0] ERR       'User-Agent': ´nodejs-cloudant/${pkg.version} (Node.js ${process.version`
`2018-01-15T10:11:54.40+0100 [APP/PROC/WEB/0] ERR`                     ^
`2018-01-15T10:11:54.40+0100 [APP/PROC/WEB/0] ERR SyntaxError: Unexpected token ILLEGAL`
`2018-01-15T10:11:54.40+0100 [APP/PROC/WEB/0] ERR     at Module._compile (module.js:439:25)`
`2018-01-15T10:11:54.40+0100 [APP/PROC/WEB/0] ERR     at Object.Module._extensions..js(module.js:474:10)`
`2018-01-15T10:11:54.40+0100 [APP/PROC/WEB/0] ERR     at Module.load (module.js:356:32)`
`2018-01-15T10:11:54.40+0100 [APP/PROC/WEB/0] ERR     at Function.Module._load (module.js:312:12)`
`2018-01-15T10:11:54.40+0100 [APP/PROC/WEB/0] ERR     at Module.require (module.js:364:17)`
`2018-01-15T10:11:54.40+0100 [APP/PROC/WEB/0] ERR     at require (module.js:380:17)`
`2018-01-15T10:11:54.40+0100 [APP/PROC/WEB/0] ERR     at Object.<anonymous> (/home/vcap/app/app.js:23:16)`
`2018-01-15T10:11:54.40+0100 [APP/PROC/WEB/0] ERR     at Module._compile (module.js:456:26)`
`2018-01-15T10:11:54.40+0100 [APP/PROC/WEB/0] ERR     at Object.Module._extensions..js (module.js:474:10)`
`2018-01-15T10:11:54.40+0100 [APP/PROC/WEB/0] ERR     at Module.load (module.js:356:32)`

Any ideas what is wrong? I cannot seem to figure out where to find the file the error is in in order to edit it.

**Comment by CorinneBacle** [comment]
Hello,
Seams that changing cloudant by @cloudant/cloudant in both app.js and package.json solve the issue.
