### ISSUE TITLE
Collision on host name

### ISSUE THREAD

**Issue by nedgar** [ibm-watson-iot/html5-phone#8]
The manifest file hardwires a host name:
`host: iot-phone`
so when Deploy to Bluemix creates a toolchain and kicks of a pipeline run, even though the `cf push` gets a unique app name, the static host name is used and collides with some existing route:
```
Creating app iot-html5-phone-20171004230227729 in org Nick_E / space dev as nick_edgar@ca.ibm.com...
OK

Creating route iot-phone.mybluemix.net...
OK

FAILED
Server error, status code: 400, error code: 210003, message: The host is taken: iot-phone

Finished: FAILED
```

The workaround is to edit the deployment script to use the app name as host name:
`cf push "${CF_APP}" -n "${CF_APP}"`

**Comment by durera** [comment]
host has been removed from the manifest as part of one of the PRs merged today, so closing this issue
